import esbuild from "esbuild";
import process from "process";
import path from "node:path";
import fs from "node:fs/promises";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// For local development, set OBSIDIAN_PLUGIN_DIR to your vault's plugin folder
// (e.g. /path/to/Vault/.obsidian/plugins/yabacavi) and `npm run dev` will deploy
// the build straight there. Defaults to the repo root.
const outdir = prod ? "." : (process.env.OBSIDIAN_PLUGIN_DIR ?? ".");
const deploying = path.resolve(outdir) !== path.resolve(".");

// esbuild only emits main.js; Obsidian also needs manifest.json and styles.css
// alongside it, so mirror them when deploying to a vault folder.
const copyAssets = {
	name: "copy-assets",
	setup(build) {
		build.onEnd(async (result) => {
			if (result.errors.length > 0 || !deploying) return;
			await fs.mkdir(outdir, { recursive: true });
			for (const asset of ["manifest.json", "styles.css"]) {
				await fs.copyFile(asset, path.join(outdir, asset));
			}
		});
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: path.join(outdir, "main.js"),
	plugins: [copyAssets],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
